# Visualization of qadratic functions

In [4]:
import numpy as np
import plotly.graph_objects as go

In [141]:
Q = np.array([
              [1,0],
              [0,1]
])
q = np.array([-1,2]).reshape(-1,1)
print(Q)
print()
print(q)

# pointwise computation of simple quadratic functions
def simple_quadratic(X,Y):
  s = np.size(X) # lenght of data
  z = np.zeros((s,s)) # allocate matrix of points for surface plot
  for i,x1 in enumerate(X):
    for j,x2 in enumerate(Y):
      x = np.array([x1,x2]).reshape(2,1) # wanna put point in a column vector to compute function value in vectorial notation
      z[i,j] = ( (x.T @ Q @ x) + (q.T @ x) )[0,0] # computation of function value with stard formula
  return z

[[1 0]
 [0 1]]

[[-1]
 [ 2]]


In [142]:
# definition of arguments
x, y = np.linspace(-5, 5, 100), np.linspace(-5, 5, 100)

# production of function data
z = simple_quadratic(x,y)

#actual plot
fig = go.Figure(data=[go.Surface(z=z, x=x, y=y)])
fig.update_layout()
fig.show()

In [97]:
z

In [59]:
np.linspace(0, 1, sh_1)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])